PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX : <http://example.org/>
SELECT ?name ?surname
WHERE {
?a rdf:type :Flemish;
	:first_name ?name;
	:last_name ?surname.

}
