prefix : <http://default.t>
prefix xsd:<https://default_xsd.t>
prefix rdf:<http://default_rdf.t>
prefix rdfs:<http://default_rdfs.t>

SELECT ?b ?c ?d
WHERE {
	?b rdf:type :Painter;
		:first_name ?c;
		:last_name ?d.
}


