prefix : <http://default.t>
prefix xsd:<https://default_xsd.t>
prefix rdf:<http://default_rdf.t>
prefix rdfs:<http://default_rdfs.t>


INSERT {
	:r3 rdf:type :Cubist;
		:first_name "Georges";
		:last_name "Braque".
} WHERE {

}
